name: anime_lab
description: "an anime quiz app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo_splash.png
    - assets/images/quiz_1.jpg
    - assets/images/quiz_2.jpg
    - assets/images/quiz_3.jpg
    - assets/images/quiz_4.jpg
    - assets/images/quiz_5.jpg
    - assets/images/quiz_6.jpg
    - assets/images/quiz_7.jpg
    - assets/images/quiz_8.jpg
    - assets/images/quiz_9.jpg
    - assets/images/quiz_10.jpg
    - assets/images/quiz_11.jpg
    - assets/images/quiz_12.jpg
    - assets/images/quiz_13.jpg
    - assets/images/quiz_14.jpg
    - assets/images/quiz_15.jpg
    - assets/images/quiz_16.jpg
    - assets/images/quiz_17.jpg
    - assets/images/quiz_18.jpg
    - assets/images/quiz_19.jpg
    - assets/images/quiz_20.jpg
    - assets/images/congratulations.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800